name: Check for new Rules

on:
  push:
  schedule:
    - cron: '0 0 * * *'

jobs:
  check-rules:
    name: Check for new rules
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'

      - name: Cache dependencies
        uses: actions/cache@v1
        with:
          path: ~/.composer/cache/files
          key: php-8.1-composer-${{ hashFiles('composer.json') }}

      - name: Install dependencies
        run: composer update --prefer-stable --prefer-dist --no-interaction --no-progress

      - name: Fetch new rules from StyleCI
        run: bin/gen-rules

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v29.0.5

      - name: Exit if the Rules have changed
        if: steps.changed-files-specific.outputs.any_changed == 'true'
        run: exit 1
