name: Tests

on:
  push:
  pull_request:
  schedule:
    - cron: '0 0 * * *'

jobs:
  phpunit:
    name: Testing - PHP ${{ matrix.php-version }} - Laravel ${{ matrix.laravel-version }} ${{ matrix.dependency-version }}
    runs-on: ubuntu-latest
    timeout-minutes: 20
    strategy:
      fail-fast: false
      max-parallel: 15
      matrix:
        php-version: ['7.4', '8.0', '8.1']
        laravel-version: [^8.64, ^9.0]
        dependency-version: ['--prefer-lowest', '--prefer-stable']
        exclude:
          - php-version: 7.4
            laravel-version: ^9.0
          - dependency-version: '--prefer-lowest'
            laravel-version: ^9.0
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install PHP
        uses: shivammathur/setup-php@master
        with:
          php-version: ${{ matrix.php-version }}

      - name: Cache dependencies
        uses: actions/cache@v1
        with:
          path: ~/.composer/cache/files
          key: php-${{ matrix.php-version }}-composer-${{ hashFiles('composer.json') }}

      - name: Validate Composer files
        run: composer validate

      - name: Update composer.json
        run: |
          composer require illuminate/support:${{ matrix.laravel-version }} --no-update
          composer require --dev laravel/framework:${{ matrix.laravel-version }} --no-update

      - name: Install dependencies
        run: composer update ${{ matrix.dependency-version }} --prefer-dist --no-interaction --no-progress

      - name: Check for style violations
        run: vendor/bin/php-cs-fixer fix --dry-run --diff

      - name: Run test suite
        run: vendor/bin/phpunit

