name: Run Tests

on:
  push:
  pull_request:
  schedule:
    - cron: '0 0 * * *'

jobs:
  phpunit:
    name: PHP ${{ matrix.php-version }} - Laravel ${{ matrix.laravel-version }} - ${{ matrix.dependency-version }}
    runs-on: ubuntu-latest
    timeout-minutes: 20
    strategy:
      fail-fast: false
      matrix:
        php-version: ['8.0', '8.1', '8.2']
        laravel-version: [^9.34, ^10]
        dependency-version: ['prefer-stable']
        exclude:
            - php-version: 8.0
              laravel-version: ^10
              dependency-version: *
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ~/.composer/cache/files
          key: php-${{ matrix.php-version }}-composer-${{ hashFiles('composer.json') }}

      - name: Validate Composer files
        run: composer validate

      - name: Update composer.json
        run: |
          composer require illuminate/support:${{ matrix.laravel-version }} --no-update
          composer require --dev laravel/framework:${{ matrix.laravel-version }} --no-update

      - name: Install dependencies
        run: composer update --${{ matrix.dependency-version }} --prefer-dist --no-interaction --no-progress

      - name: Check for style violations
        run: PHP_CS_FIXER_IGNORE_ENV=1 vendor/bin/php-cs-fixer fix --dry-run --diff

      - name: Run test suite
        run: vendor/bin/phpunit
